/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up and create a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        id: string;
                        firstName: string;
                        lastName: string;
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Returns new user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            role: "guest" | "member" | "admin" | "organizationAdmin";
                            firstName: string;
                            lastName: string;
                            phoneNumber?: string;
                            /** Format: email */
                            email: string;
                            locale: string;
                            /** @enum {string} */
                            status?: "active" | "inactive" | "suspended";
                            homeCountry: string;
                            /** Format: uri */
                            profileImage: string;
                            lastLogin: number;
                            marketingOptIn: boolean;
                            createdAt: number;
                            updatedAt: number;
                        }[];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Gateway Timeout */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API Health Status
         * @description Verifies the operational status of the API and returns a success message.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API is healthy and running. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description A simple confirmation message indicating the API is operational.
                             * @example API is healthy!
                             */
                            message: string;
                        };
                    };
                };
                /** @description An unexpected server error occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Details about the internal server error.
                             * @example Internal server error during health check.
                             */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an image file */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        file?: unknown;
                    };
                };
            };
            responses: {
                /** @description Returns image URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            image_url: string;
                        };
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notifications with pagination and filtering */
        get: {
            parameters: {
                query?: {
                    sortby?: "sent_at";
                    page?: number;
                    page_size?: number;
                    venue_id?: string;
                    user_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            title: string;
                            body: string;
                            link?: string;
                            sent_at: string;
                            /** @enum {string} */
                            notification_status: "read" | "unread";
                        }[];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new notification */
        post: {
            parameters: {
                query: {
                    venue_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        target_user_types: string[];
                        title: string;
                        body: string;
                        link: string;
                    };
                };
            };
            responses: {
                /** @description Notification created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Gateway Timeout */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notification_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update notification status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notification_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        notification_status: "read" | "unread";
                    };
                };
            };
            responses: {
                /** @description Status updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            role: "guest" | "member" | "admin" | "organizationAdmin";
                            firstName: string;
                            lastName: string;
                            phoneNumber?: string;
                            /** Format: email */
                            email: string;
                            locale: string;
                            /** @enum {string} */
                            status?: "active" | "inactive" | "suspended";
                            homeCountry: string;
                            /** Format: uri */
                            profileImage: string;
                            lastLogin: number;
                            marketingOptIn: boolean;
                            createdAt: number;
                            updatedAt: number;
                        };
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        id: string;
                        firstName: string;
                        lastName: string;
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Returns created user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            role: "guest" | "member" | "admin" | "organizationAdmin";
                            firstName: string;
                            lastName: string;
                            phoneNumber?: string;
                            /** Format: email */
                            email: string;
                            locale: string;
                            /** @enum {string} */
                            status?: "active" | "inactive" | "suspended";
                            homeCountry: string;
                            /** Format: uri */
                            profileImage: string;
                            lastLogin: number;
                            marketingOptIn: boolean;
                            createdAt: number;
                            updatedAt: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** Update user information */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        firstName?: string;
                        lastName?: string;
                        email?: string;
                        contactNumber?: string;
                        photo?: string;
                        home_location?: string;
                    };
                };
            };
            responses: {
                /** @description Returns updated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            role: "guest" | "member" | "admin" | "organizationAdmin";
                            firstName: string;
                            lastName: string;
                            phoneNumber?: string;
                            /** Format: email */
                            email: string;
                            locale: string;
                            /** @enum {string} */
                            status?: "active" | "inactive" | "suspended";
                            homeCountry: string;
                            /** Format: uri */
                            profileImage: string;
                            lastLogin: number;
                            marketingOptIn: boolean;
                            createdAt: number;
                            updatedAt: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update staff role (Admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        role: string;
                    };
                };
            };
            responses: {
                /** @description Returns updated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            role: "guest" | "member" | "admin" | "organizationAdmin";
                            firstName: string;
                            lastName: string;
                            phoneNumber?: string;
                            /** Format: email */
                            email: string;
                            locale: string;
                            /** @enum {string} */
                            status?: "active" | "inactive" | "suspended";
                            homeCountry: string;
                            /** Format: uri */
                            profileImage: string;
                            lastLogin: number;
                            marketingOptIn: boolean;
                            createdAt: number;
                            updatedAt: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
